### ISSUE TITLE
Caw module occasionally makes the build fail

### ISSUE THREAD

**Issue by georgewatson** [zuzakistan/civilservant#235]
Sometimes, but not always, the Travis build fails on one of the `caw` tests.

**Comment by georgewatson** [comment]
See, for example, [job #1043.2](https://travis-ci.org/zuzakistan/civilservant/jobs/533235232):

```
1) caw module "before all" hook:
     Uncaught TypeError: bot.say is not a function
      at Interface.<anonymous> (modules/buttery.js:4:499)
      at Interface._onLine (readline.js:282:10)
      at Interface._normalWrite (readline.js:424:12)
      at ReadStream.ondata (readline.js:141:10)
      at addChunk (_stream_readable.js:263:12)
      at readableAddChunk (_stream_readable.js:250:11)
      at ReadStream.Readable.push (_stream_readable.js:208:10)
      at fs.read (fs.js:2051:12)
      at FSReqWrap.wrapper [as oncomplete] (fs.js:658:17)
  2) caw module Uncaught error outside test suite:
     Uncaught TypeError: Cannot read property 'currentRetry' of undefined
```
