### ISSUE TITLE
Scrabble module throws TypeError on URL

### ISSUE THREAD

**Issue by zuzak** [zuzakistan/civilservant#281]
If you send a URL, like this:
```
< human> https://example.com
```
The bot throws a stack trace:
```
Error processing message event:
TypeError: Cannot read property 'count' of undefined
    at scrabbleNotate (modules/scrabble.js:66:36)
    at computeWord (modules/scrabble.js:56:16)
    at phrase.forEach (/modules/scrabble.js:115:22)
    at Array.forEach (<anonymous>)
    at Client.message (modules/scrabble.js:113:14)
    at Client.fireEvents (modules/fireEvents.js:16:28)
    at Client.<anonymous> (plugins/listeners.js:4:11)
    [truncated]
```

I think this means #277 fails via #280.

Related to #272.

**Comment by georgewatson** [comment]
I think I fixed this in #276. That wasn't really the best place for it, but it's what happened.

The relevant change is scrabble.js:66

```javascript
if (letter in bag) {
```
