### ISSUE TITLE
Bot crashes on URL event sometimes

### ISSUE THREAD

**Issue by zuzak** [zuzakistan/civilservant#301]
```
09:37:29 < douglas> https://www.gov.uk/government/news/report-062019-train-travelling-with-doors-open-on-the-jubilee-line
09:37:30 -!- civilservant [~civilserv@unaffiliated/zuzak/bot/civilservant] has quit [Remote host closed the connection]
```

```
fs.js:129
  throw new ERR_INVALID_CALLBACK();
  ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:129:9)
    at Object.writeFile (fs.js:1159:14)
    at /home/zuzak/git/civilservant/modules/url-events.js:64:12
    at IncomingMessage.<anonymous> (/home/zuzak/git/civilservant/node_modules/bitly/index.js:81:11)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by zuzak** [comment]
I think the issue is https://github.com/zuzakistan/civilservant/blob/master/modules/url-events.js#L64

It needs to either be asynchronous (`fs.writeFile`) with a callback, or synchronous (`fs.writeFileSync`) without one.
