### ISSUE TITLE
News sources should be owo'd

### ISSUE THREAD

**Issue by zuzak** [zuzakistan/civilservant#419]
If there's no URL, the breaking news twitter functionality adds a suffix, like "― Al Jazeera".
People on Twitter seem to prefer the suffix to be owo'd.

Acceptance criteria:
* News stories with URLs should list the URL
* News stories without URLs should list the source of the news story instead
* News story sources should be owo'd ("Aw Jazeewa", "Weutews", "BBC")
* News story URLs should not be owo'd

**Comment by gauravsofat** [comment]
Hi, I'm new to the project and wish to contribute, can I take this up?

**Comment by zuzak** [comment]
Sure -- go ahead. Let us know if you need any help.

**Comment by gauravsofat** [comment]
Thanks. Had a small initial query — After cloning the repo, running `npm install`, and then following that by `npm test` led to 8 failing tests on my device. Is this expected behaviour/ did I miss some initial setup steps?

Attaching a log of the failed tests, in case that is of any help -
```

  1) countdown module
       outputs a countdown:

      AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
+ actual - expected

+ 'Article 50 expires in 3 years, 2 months, 4 hours and 30 minutes'
- 'Article 50 expires in 3 years, 1 month, 30 days and 23 hours'
                                  ^
      + expected - actual

      -Article 50 expires in 3 years, 2 months, 4 hours and 30 minutes
      +Article 50 expires in 3 years, 1 month, 30 days and 23 hours
      
      at Context.<anonymous> (test/modules/countdown.js:13:12)
      at processImmediate (internal/timers.js:456:21)

  2) countdown module
       outputs a countdown less than a year to go:

      AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
+ actual - expected

+ 'Article 50 expires in 2 months, 4 hours and 30 minutes'
- 'Article 50 expires in 1 month, 30 days and 23 hours'
                         ^
      + expected - actual

      -Article 50 expires in 2 months, 4 hours and 30 minutes
      +Article 50 expires in 1 month, 30 days and 23 hours
      
      at Context.<anonymous> (test/modules/countdown.js:19:12)
      at processImmediate (internal/timers.js:456:21)

  3) countdown module
       outputs a countdown to the second milestone once we have passed the first:

      AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
+ actual - expected

+ 'The extension request deadline expires in 3 months, 19 days, 4 hours and 30 minutes'
- 'The extension request deadline expires in 3 months, 17 days and 23 hours'
                                                        ^
      + expected - actual

      -The extension request deadline expires in 3 months, 19 days, 4 hours and 30 minutes
      +The extension request deadline expires in 3 months, 17 days and 23 hours
      
      at Context.<anonymous> (test/modules/countdown.js:25:12)
      at processImmediate (internal/timers.js:456:21)

  4) countdown module
       outputs a countdown to the third milestone once we have passed the second:

      AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
+ actual - expected

+ 'The transition period expires in 1 month, 4 hours and 30 minutes'
- 'The transition period expires in 30 days and 23 hours'
                                    ^
      + expected - actual

      -The transition period expires in 1 month, 4 hours and 30 minutes
      +The transition period expires in 30 days and 23 hours
      
      at Context.<anonymous> (test/modules/countdown.js:31:12)
      at processImmediate (internal/timers.js:456:21)

  5) countdown module
       counts down to the 60th PGE in 2025:

      AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
+ actual - expected

+ 'Polls open in 4 years, 3 months, 2 days, 12 hours and 30 minutes'
- 'Polls open in 4 years, 3 months, 2 days and 7 hours'
                                          ^
      + expected - actual

      -Polls open in 4 years, 3 months, 2 days, 12 hours and 30 minutes
      +Polls open in 4 years, 3 months, 2 days and 7 hours
      
      at Context.<anonymous> (test/modules/countdown.js:57:12)
      at processImmediate (internal/timers.js:456:21)

  6) countdown module
       outputs a py2 countdown:

      AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
+ actual - expected

+ 'Python 2.7 support expires in 3 years, 1 month, 5 hours and 30 minutes'
- 'Python 2.7 support expires in 3 years and 1 month'
                                        ^
      + expected - actual

      -Python 2.7 support expires in 3 years, 1 month, 5 hours and 30 minutes
      +Python 2.7 support expires in 3 years and 1 month
      
      at Context.<anonymous> (test/modules/countdown.js:75:12)
      at processImmediate (internal/timers.js:456:21)

  7) countdown module
       outputs a py2 countup:

      AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
+ actual - expected

+ 'Python 2.7 support expired 10 months, 30 days, 18 hours and 30 minutes ago'
- 'Python 2.7 support expired 11 months ago'
                               ^
      + expected - actual

      -Python 2.7 support expired 10 months, 30 days, 18 hours and 30 minutes ago
      +Python 2.7 support expired 11 months ago
      
      at Context.<anonymous> (test/modules/countdown.js:81:12)
      at processImmediate (internal/timers.js:456:21)

  8) radio module
       should parse the API correctly:

      AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
+ actual - expected

+ 'Now: \u000300Midnight News\u000f \u000315(20/03/2019)\u000f followed by Book of the Week in 15 minutes (6:00 am)'
- 'Now: \u000300Midnight News\u000f \u000315(20/03/2019)\u000f followed by Book of the Week in 15 minutes (12:30 am)'
      + expected - actual

      -Now: 00Midnight News 15(20/03/2019) followed by Book of the Week in 15 minutes (6:00 am)
      +Now: 00Midnight News 15(20/03/2019) followed by Book of the Week in 15 minutes (12:30 am)
      
      at Context.<anonymous> (test/modules/radio.js:35:12)

```

**Comment by zuzak** [comment]
It should work, but we've had some problems mocking the date function before. Those tests are unrelated to any of the news functionality, so it's safe to ignore them for your purposes.

**Comment by gauravsofat** [comment]
Thanks for the quick response! You can assign this issue to me, shall open a PR very soon.

**Comment by gauravsofat** [comment]
cc @zuzak to action upon the linked PR
